apiVersion: v1
kind: Pod
metadata:
  name: env-ConfigMap
spec: 
  containers:
  - name: nginx
    image: nginx
    envForm: 
      - configMapRef:
          name: pod-config
        
    envFrom:
      - secretRef:
          name: pod-secret